print("Registro")
nome=input("Digite o seu nome:")
sexo=input("Digite o seu sexo, M para msculino e F para feminino:")
idade=input("Digite o sua idade:")
arquivo=open("dados.txt","w")
arquivo.write(nome)
arquivo.write("\n")
arquivo.write(sexo)
arquivo.write("\n")
arquivo.write(idade)
arquivo.write("\n")
arquivo.close()
